train:
  split: 0.95
  epochs: 2000
  batch_size: 64
  lr: 1.0e-5
  num_plots: 6
  pretrained_loc: 'save/sine_20230809_214233/results/weights/best_model.pth' 

model:
  latent_dim: 16
  horizon: 48
  input_dim: 1


#'save/sine_20230809_180929/results/weights/best_model.pth'